### ISSUE TITLE
[Bug]: Class "NumberFormatter" not found or php-intl extension missing.

### ISSUE THREAD

**Issue by hellomohsinhello** [NativePHP/laravel#185]
### What happened?

How to change php.ini config or install php-intl extension.

### How to reproduce the bug

```
function format_number(float | int $number): string
 {

        $formatter = new NumberFormatter(app()->getLocale(), NumberFormatter::DECIMAL);

        return $formatter->format($number);
}

format_number(2);
```

This code won't run as expected.

### Package Version

0.4.0

### PHP Version

8.1

### Laravel Version

10.10

### Node Version

18.16.0

### Which operating systems does with happen with?

macOS

**Comment by MarceauKa** [comment]
Fixed it requiring ‘symfony/polyfill-intl-icu‘

**Comment by buchin** [comment]
> Fixed it requiring `symfony/polyfill-intl-icu`

Hi @MarceauKa, could you please elaborate required step to solve this issue?
I got this issue and requiring symfony/polyfill-intl-icu does not resolve it.

Thank you

**Comment by pmffromspace** [comment]
Hi I did a lot of research and this is the closest I got to an solution for this exact problem. Im trying to pack a filamenphp laravel webapp into a desktop programm with the help of nativePHP and I just cant find a way to remove the error „php extension intl not found“

@MarceauKa could you please just quickly tell us in which file (and maybe how) you fixed this?
I tried a lot of ways already, but Im unfortunatly new to php so I would really appreciate the help! :)

Kind regards

**Comment by simonhamp** [comment]
This is because the `intl` extension isn't built into the PHP binaries we're using yet.

I also noticed that it's [apparently not available for Windows](https://static-php.dev/en/guide/extensions.html) yet.

I will test and see what needs doing to get this in place on the binary side so we don't need to mess around with polyfills.

**Comment by pmffromspace** [comment]
Thanks for this quick response!

In the meantime I tried to build the php binaries manually with this approach:

```
composer require nativephp/php-bin --dev

git clone https://github.com/crazywhalecc/static-php-cli.git --depth=1
cd static-php-cli
bin/spc download --clean
bin/spc download --with-php=8.2 --for-extensions "intl,bcmath,ctype,curl,dom,fileinfo,filter,mbstring,openssl,pdo,pdo_sqlite,session,simplexml,sockets,sqlite3,tokenizer,xml,zlib"
bin/spc download --clean
bin/spc download --with-php=8.3 --for-extensions "intl,bcmath,ctype,curl,dom,fileinfo,filter,mbstring,openssl,pdo,pdo_sqlite,session,simplexml,sockets,sqlite3,tokenizer,xml,zlib"
bin/spc build --build-cli --build-embed "intl,bcmath,ctype,curl,dom,fileinfo,filter,mbstring,openssl,pdo,pdo_sqlite,session,simplexml,sockets,sqlite3,tokenizer,xml,zlib"

```
I then (Im on MacOS) right clicked the php bin and compressed it to a .zip file and renamed and replaced the supposingly old php bins at `vendor/nativephp/php-bin/bin/mac/arm64/php-8.2.zip`

But I stillt get the same error. (with `php artisan native:serve`or `php artisan native:build`)

Did I miss something when replacing the php binary or is it just not that simple?

Kind regards.

**Comment by simonhamp** [comment]
In theory, what you've done is correct...

What version of PHP are you running locally? `php -v`

**Comment by pmffromspace** [comment]
`PHP 8.3.6 (cli) (built: Apr 12 2024 00:13:56) (NTS)`

maybe I should zip it using a cli tool?

**Comment by simonhamp** [comment]
So the thing to check is if the PHP you've built actually includes `intl`

So you can check the PHP8.3 binary you generated:

```
/path/to/binary/php -i | grep intl
```

**Comment by pmffromspace** [comment]
I get following (I cant interpret if this is sufficient)

`cd <directroy-of-generated-php-bin>`
`./php-8.3 -i | grep intl`

Output:
```
intl
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => Off => Off
```

**Comment by simonhamp** [comment]
That means intl extension is enabled and working

**Comment by simonhamp** [comment]
It's possible that even after copying it into the vendor folder it gets wiped away

Can you also check the version that gets built into the app?

**Comment by pmffromspace** [comment]
Im having trouble finding a way to check that - in the developer tools I cant find the php version. Im also unable to build php-8.1.
How would I check the final build php version?

**Comment by simonhamp** [comment]
There are some [instructions in the docs](https://nativephp.com/docs/getting-started/debugging#check-your-app-and-php)
