### ISSUE TITLE
[Bug]: Error when running `php artisan native:serve` on a new laravel app

### ISSUE THREAD

**Issue by abishekrsrikaanth** [NativePHP/laravel#253]
### What happened?

Getting this error when running php artisan native:serve
```
2024-02-23 21:04:54.236 Electron[72786:85584652] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

Error: Command failed: /Users/abisheksrikaanth/projects/appname/desktop-app/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 255,
  killed: false,
  signal: null,
  cmd: '/Users/abisheksrikaanth/projects/appname/desktop-app/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config',
  stdout: '\n' +
    'Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.17. in /Users/abisheksrikaanth/projects/appname/desktop-app/vendor/composer/platform_check.php on line 24\n',
  stderr: ''
}
```
output of php -v is the following. I am Mac. Native PHP Version 0.4.0 and on Laravel 10.45.1
```
PHP 8.3.1 (cli) (built: Dec 20 2023 12:44:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.1, Copyright (c), by Zend Technologies
```
Any ideas how to fix this? Not sure why the error says that I am php 8.1.17 though, although the php version on composer.json is "php": "^8.1", 

### How to reproduce the bug

```
laravel new app-name
composer require nativephp/electron
php artisan native:install
php artisan migrate
php artisan native:serve
```

### Package Version

0.4.0

### PHP Version

8.3.1

### Laravel Version

10.45.1

### Node Version

21.6.2

### Which operating systems does with happen with?

macOS

**Comment by abishekrsrikaanth** [comment]
Ref: https://github.com/electron/electron/issues/40318 for one of the issues solved in a recent electron release

**Comment by sfolador** [comment]
Hi @abishekrsrikaanth , did you manage to solve this? 

I still receive this error:   'Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.17. 
I have Sonoma 14.3.1 and PHP 8.3 with an Intel Mac.

The only way to make it work is by using PHP 8.1 in my system, which I would like to avoid.

**Comment by abishekrsrikaanth** [comment]
haven't figured out a fix yet. I copied the PHP libraries from Laravel Herd into the project directory as a temporary fix. I'm still not sure if I would have problems with the build.

**Comment by Baspa** [comment]
Got this same error as well, any fix yet?
